name: Sync NHL Games Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 2h UTC
  workflow_dispatch:     # Permet de le lancer manuellement depuis GitHub

jobs:
  run-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run NHL fetcher script
        run: node fetchLastGamesForAllTeams.js
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
